name: Deploy Container App to Azure

on:
  push:
    branches:
      - main

env:
  REGISTRY_LOGIN_SERVER: '<YOUR_REGISTRY_LOGIN_SERVER>'
  IMAGE_BASE_NAME: '<YOUR_IMAGE_NAME>'
  RESOURCE_GROUP: 'aguadamillas_students_1'
  WEBAPP_NAME: '<YOUR_WEBAPP_NAME>'
  APP_SERVICE_PLAN: '<YOUR_APP_SERVICE_PLAN_NAME>'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@main

    - name: Login to Azure
      uses: azure/login@v1

    - name: Login to ACR
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.REGISTRY_LOGIN_SERVER }}

    - name: Set image version
      id: image-version
      run: echo "::set-output name=version::$(echo ${GITHUB_REF#refs/heads/})-$(date +'%Y.%m.%d.%H.%M')"

    - name: Build and Push Docker Image
      run: |
        docker build . -t ${{ env.REGISTRY_LOGIN_SERVER }}/${{env.IMAGE_BASE_NAME}}:${{ steps.image-version.outputs.version }}
        docker push ${{ env.REGISTRY_LOGIN_SERVER }}/${{env.IMAGE_BASE_NAME}}:${{ steps.image-version.outputs.version }}

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
    - name: Login to Azure
      uses: azure/login@v1

    - name: Deploy Docker Image to Azure Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name: ${{ env.WEBAPP_NAME }}
        images: |
          ${{ env.REGISTRY_LOGIN_SERVER }}/${{ env.IMAGE_BASE_NAME }}:${{ needs.build-and-push.outputs['image-version.version'] }}